FROM ubuntu:latest

RUN apt-update && apt-get install -y \
    python3.10 \
    python3-pip \
    git

RUN pip3 install PyYAML

COPY feed.py /usr/bin/feed.py

COPY entryPoint.sh /entryPoint.sh

ENTRYPOINT [ "/entryPoint.sh" ]